CREATE TABLE IF NOT EXISTS mayors (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    cidade_id INT UNSIGNED,
    PRIMARY KEY (id),
    FOREIGN KEY (cidade_id) REFERENCES cities (id)
);